// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeCode(arg1:string,arg2:string):Promise<string>;

export function CancelRunningCommand():Promise<boolean>;

export function CheckModalInstalled():Promise<boolean>;

export function ClearExecutionLogs(arg1:string):Promise<void>;

export function CreateAIConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number):Promise<main.AIConfig>;

export function CreateExecutionLog(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:Record<string, string>):Promise<string>;

export function CreateModalApp(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<main.ModalApp>;

export function CreateProject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.Project>;

export function CreateProjectFromTemplate(arg1:string,arg2:string,arg3:string):Promise<main.Project>;

export function CreateScript(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function DeleteAIConfig(arg1:string):Promise<void>;

export function DeleteExecutionLog(arg1:string):Promise<void>;

export function DeleteModalApp(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteScript(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeployScript(arg1:string,arg2:string):Promise<main.CommandResult>;

export function DeployScriptAsync(arg1:string,arg2:string):Promise<void>;

export function DeployScriptWithContent(arg1:string,arg2:string,arg3:string):Promise<main.CommandResult>;

export function DeployScriptWithContentAsync(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeployScriptWithLogAsync(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:Record<string, string>):Promise<string>;

export function DetectInstalledIDEs():Promise<Array<main.IDEConfig>>;

export function ExecuteModalCommand(arg1:string):Promise<string>;

export function ExecuteModalCommandWithToken(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FormatPythonCode(arg1:string):Promise<string>;

export function GetAIConfigs():Promise<Array<main.AIConfig>>;

export function GetDefaultAIConfig():Promise<main.AIConfig>;

export function GetExecutionLogDetail(arg1:string):Promise<main.ExecutionLog>;

export function GetExecutionLogs(arg1:string,arg2:number):Promise<Array<main.ExecutionLog>>;

export function GetGlobalVariables():Promise<Record<string, string>>;

export function GetModalAppByID(arg1:string):Promise<main.ModalApp>;

export function GetModalAppList():Promise<Array<main.ModalApp>>;

export function GetModalApps():Promise<main.CommandResult>;

export function GetProjectVariables(arg1:string):Promise<Record<string, string>>;

export function GetProjects():Promise<Array<main.Project>>;

export function GetScripts(arg1:string):Promise<Array<main.Script>>;

export function Log(arg1:main.LogType,arg2:string):Promise<void>;

export function LogError(arg1:string):Promise<void>;

export function LogInfo(arg1:string):Promise<void>;

export function LogWarning(arg1:string):Promise<void>;

export function ModalAppDeleteWithTokenPair(arg1:string,arg2:string,arg3:string):Promise<main.CommandResult>;

export function ModalAppDescribeWithTokenPair(arg1:string,arg2:string,arg3:string):Promise<main.CommandResult>;

export function ModalAppHistoryWithTokenPair(arg1:string,arg2:string,arg3:string):Promise<main.CommandResult>;

export function ModalAppList():Promise<main.CommandResult>;

export function ModalAppListWithToken(arg1:string):Promise<main.CommandResult>;

export function ModalAppListWithTokenPair(arg1:string,arg2:string):Promise<main.CommandResult>;

export function ModalAppLogs(arg1:string):Promise<main.CommandResult>;

export function ModalAppLogsWithToken(arg1:string,arg2:string):Promise<main.CommandResult>;

export function ModalAppLogsWithTokenPair(arg1:string,arg2:string,arg3:string):Promise<main.CommandResult>;

export function ModalAppStatsWithTokenPair(arg1:string,arg2:string,arg3:string):Promise<main.CommandResult>;

export function ModalAppStop(arg1:string):Promise<main.CommandResult>;

export function ModalAppStopWithToken(arg1:string,arg2:string):Promise<main.CommandResult>;

export function ModalAppStopWithTokenPair(arg1:string,arg2:string,arg3:string):Promise<main.CommandResult>;

export function ModalContainerExecWithTokenPair(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.CommandResult>;

export function ModalContainerList():Promise<main.CommandResult>;

export function ModalContainerListWithToken(arg1:string):Promise<main.CommandResult>;

export function ModalContainerListWithTokenPair(arg1:string,arg2:string):Promise<main.CommandResult>;

export function ModalContainerStopWithTokenPair(arg1:string,arg2:string,arg3:string):Promise<main.CommandResult>;

export function ModalEnvironmentListWithTokenPair(arg1:string,arg2:string):Promise<main.CommandResult>;

export function ModalNfsListWithTokenPair(arg1:string,arg2:string):Promise<main.CommandResult>;

export function ModalProfileWithTokenPair(arg1:string,arg2:string):Promise<main.CommandResult>;

export function ModalSecretList():Promise<main.CommandResult>;

export function ModalSecretListWithToken(arg1:string):Promise<main.CommandResult>;

export function ModalSecretListWithTokenPair(arg1:string,arg2:string):Promise<main.CommandResult>;

export function ModalTokenNew():Promise<main.CommandResult>;

export function ModalTokenSet(arg1:string,arg2:string):Promise<main.CommandResult>;

export function ModalVolumeDeleteWithTokenPair(arg1:string,arg2:string,arg3:string):Promise<main.CommandResult>;

export function ModalVolumeGetWithTokenPair(arg1:string,arg2:string,arg3:string):Promise<main.CommandResult>;

export function ModalVolumeList():Promise<main.CommandResult>;

export function ModalVolumeListWithToken(arg1:string):Promise<main.CommandResult>;

export function ModalVolumeListWithTokenPair(arg1:string,arg2:string):Promise<main.CommandResult>;

export function ModalVolumeLsWithTokenPair(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.CommandResult>;

export function ModalVolumePutAsyncWithTokenPair(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.CommandResult>;

export function ModalVolumePutWithTokenPair(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.CommandResult>;

export function ModalVolumeRmWithTokenPair(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.CommandResult>;

export function MoveScript(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenInIDE(arg1:string,arg2:string):Promise<void>;

export function ReadScriptContent(arg1:string):Promise<string>;

export function ReorderScripts(arg1:string,arg2:Array<string>):Promise<void>;

export function RunModalCommand(arg1:string,arg2:Array<string>,arg3:string):Promise<main.CommandResult>;

export function RunModalCommandAsync(arg1:string,arg2:Array<string>,arg3:string,arg4:string,arg5:string):Promise<void>;

export function RunModalCommandAsyncWithLog(arg1:string,arg2:Array<string>,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function RunModalCommandWithEnv(arg1:string,arg2:Array<string>,arg3:string,arg4:string,arg5:string):Promise<main.CommandResult>;

export function RunModalCommandWithToken(arg1:string,arg2:Array<string>,arg3:string):Promise<main.CommandResult>;

export function RunModalCommandWithTokenPair(arg1:string,arg2:Array<string>,arg3:string,arg4:string,arg5:string):Promise<main.CommandResult>;

export function RunScript(arg1:string,arg2:string):Promise<main.CommandResult>;

export function RunScriptAsync(arg1:string,arg2:string):Promise<void>;

export function RunScriptWithArgsAsync(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RunScriptWithContentAsync(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RunScriptWithLogAsync(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:Record<string, string>):Promise<string>;

export function SaveAIConfigs(arg1:Array<main.AIConfig>):Promise<void>;

export function SaveModalAppList(arg1:Array<main.ModalApp>):Promise<void>;

export function SaveProjects(arg1:Array<main.Project>):Promise<void>;

export function SaveScriptContent(arg1:string,arg2:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectModelFile():Promise<string>;

export function SetDefaultAIConfig(arg1:string):Promise<void>;

export function SetGlobalVariables(arg1:Record<string, string>):Promise<void>;

export function SetProjectVariables(arg1:string,arg2:Record<string, string>):Promise<void>;

export function StopApp(arg1:string):Promise<main.CommandResult>;

export function TestAIConnection(arg1:string,arg2:string,arg3:string):Promise<string>;

export function TestModalConnection(arg1:string,arg2:string):Promise<main.CommandResult>;

export function UpdateAIConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:number):Promise<void>;

export function UpdateExecutionLog(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateModalApp(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function UpdateProject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateScript(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
