// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeCode(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeCode'](arg1, arg2);
}

export function CancelRunningCommand() {
  return window['go']['main']['App']['CancelRunningCommand']();
}

export function CheckModalInstalled() {
  return window['go']['main']['App']['CheckModalInstalled']();
}

export function ClearExecutionLogs(arg1) {
  return window['go']['main']['App']['ClearExecutionLogs'](arg1);
}

export function CreateAIConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateAIConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateExecutionLog(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateExecutionLog'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateModalApp(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateModalApp'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3, arg4);
}

export function CreateProjectFromTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProjectFromTemplate'](arg1, arg2, arg3);
}

export function CreateScript(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateScript'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteAIConfig(arg1) {
  return window['go']['main']['App']['DeleteAIConfig'](arg1);
}

export function DeleteExecutionLog(arg1) {
  return window['go']['main']['App']['DeleteExecutionLog'](arg1);
}

export function DeleteModalApp(arg1) {
  return window['go']['main']['App']['DeleteModalApp'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteScript(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteScript'](arg1, arg2, arg3);
}

export function DeployScript(arg1, arg2) {
  return window['go']['main']['App']['DeployScript'](arg1, arg2);
}

export function DeployScriptAsync(arg1, arg2) {
  return window['go']['main']['App']['DeployScriptAsync'](arg1, arg2);
}

export function DeployScriptWithContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeployScriptWithContent'](arg1, arg2, arg3);
}

export function DeployScriptWithContentAsync(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeployScriptWithContentAsync'](arg1, arg2, arg3);
}

export function DeployScriptWithLogAsync(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['DeployScriptWithLogAsync'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DetectInstalledIDEs() {
  return window['go']['main']['App']['DetectInstalledIDEs']();
}

export function ExecuteModalCommand(arg1) {
  return window['go']['main']['App']['ExecuteModalCommand'](arg1);
}

export function ExecuteModalCommandWithToken(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteModalCommandWithToken'](arg1, arg2, arg3);
}

export function FormatPythonCode(arg1) {
  return window['go']['main']['App']['FormatPythonCode'](arg1);
}

export function GetAIConfigs() {
  return window['go']['main']['App']['GetAIConfigs']();
}

export function GetDefaultAIConfig() {
  return window['go']['main']['App']['GetDefaultAIConfig']();
}

export function GetExecutionLogDetail(arg1) {
  return window['go']['main']['App']['GetExecutionLogDetail'](arg1);
}

export function GetExecutionLogs(arg1, arg2) {
  return window['go']['main']['App']['GetExecutionLogs'](arg1, arg2);
}

export function GetGlobalVariables() {
  return window['go']['main']['App']['GetGlobalVariables']();
}

export function GetModalAppByID(arg1) {
  return window['go']['main']['App']['GetModalAppByID'](arg1);
}

export function GetModalAppList() {
  return window['go']['main']['App']['GetModalAppList']();
}

export function GetModalApps() {
  return window['go']['main']['App']['GetModalApps']();
}

export function GetProjectVariables(arg1) {
  return window['go']['main']['App']['GetProjectVariables'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetScripts(arg1) {
  return window['go']['main']['App']['GetScripts'](arg1);
}

export function Log(arg1, arg2) {
  return window['go']['main']['App']['Log'](arg1, arg2);
}

export function LogError(arg1) {
  return window['go']['main']['App']['LogError'](arg1);
}

export function LogInfo(arg1) {
  return window['go']['main']['App']['LogInfo'](arg1);
}

export function LogWarning(arg1) {
  return window['go']['main']['App']['LogWarning'](arg1);
}

export function ModalAppDeleteWithTokenPair(arg1, arg2, arg3) {
  return window['go']['main']['App']['ModalAppDeleteWithTokenPair'](arg1, arg2, arg3);
}

export function ModalAppDescribeWithTokenPair(arg1, arg2, arg3) {
  return window['go']['main']['App']['ModalAppDescribeWithTokenPair'](arg1, arg2, arg3);
}

export function ModalAppHistoryWithTokenPair(arg1, arg2, arg3) {
  return window['go']['main']['App']['ModalAppHistoryWithTokenPair'](arg1, arg2, arg3);
}

export function ModalAppList() {
  return window['go']['main']['App']['ModalAppList']();
}

export function ModalAppListWithToken(arg1) {
  return window['go']['main']['App']['ModalAppListWithToken'](arg1);
}

export function ModalAppListWithTokenPair(arg1, arg2) {
  return window['go']['main']['App']['ModalAppListWithTokenPair'](arg1, arg2);
}

export function ModalAppLogs(arg1) {
  return window['go']['main']['App']['ModalAppLogs'](arg1);
}

export function ModalAppLogsWithToken(arg1, arg2) {
  return window['go']['main']['App']['ModalAppLogsWithToken'](arg1, arg2);
}

export function ModalAppLogsWithTokenPair(arg1, arg2, arg3) {
  return window['go']['main']['App']['ModalAppLogsWithTokenPair'](arg1, arg2, arg3);
}

export function ModalAppStatsWithTokenPair(arg1, arg2, arg3) {
  return window['go']['main']['App']['ModalAppStatsWithTokenPair'](arg1, arg2, arg3);
}

export function ModalAppStop(arg1) {
  return window['go']['main']['App']['ModalAppStop'](arg1);
}

export function ModalAppStopWithToken(arg1, arg2) {
  return window['go']['main']['App']['ModalAppStopWithToken'](arg1, arg2);
}

export function ModalAppStopWithTokenPair(arg1, arg2, arg3) {
  return window['go']['main']['App']['ModalAppStopWithTokenPair'](arg1, arg2, arg3);
}

export function ModalContainerExecWithTokenPair(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ModalContainerExecWithTokenPair'](arg1, arg2, arg3, arg4);
}

export function ModalContainerList() {
  return window['go']['main']['App']['ModalContainerList']();
}

export function ModalContainerListWithToken(arg1) {
  return window['go']['main']['App']['ModalContainerListWithToken'](arg1);
}

export function ModalContainerListWithTokenPair(arg1, arg2) {
  return window['go']['main']['App']['ModalContainerListWithTokenPair'](arg1, arg2);
}

export function ModalContainerStopWithTokenPair(arg1, arg2, arg3) {
  return window['go']['main']['App']['ModalContainerStopWithTokenPair'](arg1, arg2, arg3);
}

export function ModalEnvironmentListWithTokenPair(arg1, arg2) {
  return window['go']['main']['App']['ModalEnvironmentListWithTokenPair'](arg1, arg2);
}

export function ModalNfsListWithTokenPair(arg1, arg2) {
  return window['go']['main']['App']['ModalNfsListWithTokenPair'](arg1, arg2);
}

export function ModalProfileWithTokenPair(arg1, arg2) {
  return window['go']['main']['App']['ModalProfileWithTokenPair'](arg1, arg2);
}

export function ModalSecretList() {
  return window['go']['main']['App']['ModalSecretList']();
}

export function ModalSecretListWithToken(arg1) {
  return window['go']['main']['App']['ModalSecretListWithToken'](arg1);
}

export function ModalSecretListWithTokenPair(arg1, arg2) {
  return window['go']['main']['App']['ModalSecretListWithTokenPair'](arg1, arg2);
}

export function ModalTokenNew() {
  return window['go']['main']['App']['ModalTokenNew']();
}

export function ModalTokenSet(arg1, arg2) {
  return window['go']['main']['App']['ModalTokenSet'](arg1, arg2);
}

export function ModalVolumeDeleteWithTokenPair(arg1, arg2, arg3) {
  return window['go']['main']['App']['ModalVolumeDeleteWithTokenPair'](arg1, arg2, arg3);
}

export function ModalVolumeGetWithTokenPair(arg1, arg2, arg3) {
  return window['go']['main']['App']['ModalVolumeGetWithTokenPair'](arg1, arg2, arg3);
}

export function ModalVolumeList() {
  return window['go']['main']['App']['ModalVolumeList']();
}

export function ModalVolumeListWithToken(arg1) {
  return window['go']['main']['App']['ModalVolumeListWithToken'](arg1);
}

export function ModalVolumeListWithTokenPair(arg1, arg2) {
  return window['go']['main']['App']['ModalVolumeListWithTokenPair'](arg1, arg2);
}

export function ModalVolumeLsWithTokenPair(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ModalVolumeLsWithTokenPair'](arg1, arg2, arg3, arg4);
}

export function ModalVolumePutAsyncWithTokenPair(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ModalVolumePutAsyncWithTokenPair'](arg1, arg2, arg3, arg4, arg5);
}

export function ModalVolumePutWithTokenPair(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ModalVolumePutWithTokenPair'](arg1, arg2, arg3, arg4, arg5);
}

export function ModalVolumeRmWithTokenPair(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ModalVolumeRmWithTokenPair'](arg1, arg2, arg3, arg4);
}

export function MoveScript(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveScript'](arg1, arg2, arg3);
}

export function OpenInIDE(arg1, arg2) {
  return window['go']['main']['App']['OpenInIDE'](arg1, arg2);
}

export function ReadScriptContent(arg1) {
  return window['go']['main']['App']['ReadScriptContent'](arg1);
}

export function ReorderScripts(arg1, arg2) {
  return window['go']['main']['App']['ReorderScripts'](arg1, arg2);
}

export function RunModalCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunModalCommand'](arg1, arg2, arg3);
}

export function RunModalCommandAsync(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RunModalCommandAsync'](arg1, arg2, arg3, arg4, arg5);
}

export function RunModalCommandAsyncWithLog(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RunModalCommandAsyncWithLog'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RunModalCommandWithEnv(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RunModalCommandWithEnv'](arg1, arg2, arg3, arg4, arg5);
}

export function RunModalCommandWithToken(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunModalCommandWithToken'](arg1, arg2, arg3);
}

export function RunModalCommandWithTokenPair(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RunModalCommandWithTokenPair'](arg1, arg2, arg3, arg4, arg5);
}

export function RunScript(arg1, arg2) {
  return window['go']['main']['App']['RunScript'](arg1, arg2);
}

export function RunScriptAsync(arg1, arg2) {
  return window['go']['main']['App']['RunScriptAsync'](arg1, arg2);
}

export function RunScriptWithArgsAsync(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunScriptWithArgsAsync'](arg1, arg2, arg3);
}

export function RunScriptWithContentAsync(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunScriptWithContentAsync'](arg1, arg2, arg3);
}

export function RunScriptWithLogAsync(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['RunScriptWithLogAsync'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SaveAIConfigs(arg1) {
  return window['go']['main']['App']['SaveAIConfigs'](arg1);
}

export function SaveModalAppList(arg1) {
  return window['go']['main']['App']['SaveModalAppList'](arg1);
}

export function SaveProjects(arg1) {
  return window['go']['main']['App']['SaveProjects'](arg1);
}

export function SaveScriptContent(arg1, arg2) {
  return window['go']['main']['App']['SaveScriptContent'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2, arg3);
}

export function SelectModelFile() {
  return window['go']['main']['App']['SelectModelFile']();
}

export function SetDefaultAIConfig(arg1) {
  return window['go']['main']['App']['SetDefaultAIConfig'](arg1);
}

export function SetGlobalVariables(arg1) {
  return window['go']['main']['App']['SetGlobalVariables'](arg1);
}

export function SetProjectVariables(arg1, arg2) {
  return window['go']['main']['App']['SetProjectVariables'](arg1, arg2);
}

export function StopApp(arg1) {
  return window['go']['main']['App']['StopApp'](arg1);
}

export function TestAIConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestAIConnection'](arg1, arg2, arg3);
}

export function TestModalConnection(arg1, arg2) {
  return window['go']['main']['App']['TestModalConnection'](arg1, arg2);
}

export function UpdateAIConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateAIConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateExecutionLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateExecutionLog'](arg1, arg2, arg3);
}

export function UpdateModalApp(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateModalApp'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2, arg3, arg4);
}

export function UpdateScript(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateScript'](arg1, arg2, arg3, arg4);
}
